### ISSUE TITLE
 CircleCI

### ISSUE THREAD

**Issue by sarovin** [frostney/react-native-notification#6]
Do you want migrate from Travis to [CircleCi](https://circleci.com/)?
@frostney

**Comment by frostney** [comment]
We definitely can. I'm a big fan of CircleCI, I've been using it for a while in closed source projects.

I originally thought to only mock React Native with `react-native-mock` and then write unit test in AVA and Enzyme which would just check for the core functionality (is something rendered, do we get the correct output, is `componentDidMount` triggered, etc.). In that case the CI environment doesn't really matter and Travis would be fine.
The advantage I see in CircleCI is that we could run unit tests on a real simulator. However, I don't really know how to set that up. Feel free to get that going though.

**Comment by sarovin** [comment]
You're right, Travis CI is best for us.
